// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6tsvjI0xcxbKmqztCB3QlEMQTc_WM-N0',
    appId: '1:1011631212965:web:7d081e45652c7d844ac04c',
    messagingSenderId: '1011631212965',
    projectId: 'fasum-apps-43898',
    authDomain: 'fasum-apps-43898.firebaseapp.com',
    storageBucket: 'fasum-apps-43898.firebasestorage.app',
    measurementId: 'G-MGDPBDLHJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABXE7We1evTcJm5ahJzA8BOwLjTLVFwwk',
    appId: '1:1011631212965:android:5be842d667b255f64ac04c',
    messagingSenderId: '1011631212965',
    projectId: 'fasum-apps-43898',
    storageBucket: 'fasum-apps-43898.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6tsvjI0xcxbKmqztCB3QlEMQTc_WM-N0',
    appId: '1:1011631212965:web:a9512b804f72bd4c4ac04c',
    messagingSenderId: '1011631212965',
    projectId: 'fasum-apps-43898',
    authDomain: 'fasum-apps-43898.firebaseapp.com',
    storageBucket: 'fasum-apps-43898.firebasestorage.app',
    measurementId: 'G-HN5WMEKR6G',
  );
}