// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-FEPQOljw-iD5o9XgdiiLa3WwPRwc_M',
    appId: '1:531583580649:android:d1d4f84a139e39021cf378',
    messagingSenderId: '531583580649',
    projectId: 'fasum-app-c6315',
    storageBucket: 'fasum-app-c6315.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBk4CaHGfWFppofVPP99a3XjWdbVV-9aHA',
    appId: '1:531583580649:web:6fb0fe8c814a82f31cf378',
    messagingSenderId: '531583580649',
    projectId: 'fasum-app-c6315',
    authDomain: 'fasum-app-c6315.firebaseapp.com',
    storageBucket: 'fasum-app-c6315.firebasestorage.app',
    measurementId: 'G-H1X8PNMECG',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBk4CaHGfWFppofVPP99a3XjWdbVV-9aHA',
    appId: '1:531583580649:web:6fb0fe8c814a82f31cf378',
    messagingSenderId: '531583580649',
    projectId: 'fasum-app-c6315',
    authDomain: 'fasum-app-c6315.firebaseapp.com',
    storageBucket: 'fasum-app-c6315.firebasestorage.app',
    measurementId: 'G-H1X8PNMECG',
  );

}