// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA0mAg40UKL1bL4SrFKaX3mQdD7z-bnYg',
    appId: '1:929683562411:web:635fc53a74c11493e0fcee',
    messagingSenderId: '929683562411',
    projectId: 'first-app-2af22',
    authDomain: 'first-app-2af22.firebaseapp.com',
    databaseURL: 'https://first-app-2af22-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2af22.firebasestorage.app',
    measurementId: 'G-VC51J9SPCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKJjpr5DPgxMEjE_glq2u2g_11hV2XMAk',
    appId: '1:929683562411:android:6a5d0496b9f7f0eae0fcee',
    messagingSenderId: '929683562411',
    projectId: 'first-app-2af22',
    databaseURL: 'https://first-app-2af22-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2af22.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJj4LobuM2cTpHFpIec9gLMPr5zwEtBrw',
    appId: '1:929683562411:ios:ef05958985f07e81e0fcee',
    messagingSenderId: '929683562411',
    projectId: 'first-app-2af22',
    databaseURL: 'https://first-app-2af22-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2af22.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJj4LobuM2cTpHFpIec9gLMPr5zwEtBrw',
    appId: '1:929683562411:ios:ef05958985f07e81e0fcee',
    messagingSenderId: '929683562411',
    projectId: 'first-app-2af22',
    databaseURL: 'https://first-app-2af22-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2af22.firebasestorage.app',
    iosBundleId: 'com.example.daftarBelanja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBA0mAg40UKL1bL4SrFKaX3mQdD7z-bnYg',
    appId: '1:929683562411:web:5cc3e57d3d82dcd4e0fcee',
    messagingSenderId: '929683562411',
    projectId: 'first-app-2af22',
    authDomain: 'first-app-2af22.firebaseapp.com',
    databaseURL: 'https://first-app-2af22-default-rtdb.firebaseio.com',
    storageBucket: 'first-app-2af22.firebasestorage.app',
    measurementId: 'G-RV581PG0H0',
  );
}
